from setuptools import setup, find_packages

setup(
    name="mock-project",
    version="0.1.0",
    description="A mock Python project for testing dependency removal tools",
    author="Mock Author",
    author_email="mock@example.com",
    url="https://github.com/example/mock-project",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "requests>=2.25.0",
        "pandas>=1.3.0",
        "numpy>=1.21.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "scikit-learn>=1.0.0",
        "flask>=2.0.0",
        "django>=4.0.0",
        "fastapi>=0.68.0",
        "sqlalchemy>=1.4.0",
        "psycopg2-binary>=2.9.0",
        "redis>=4.0.0",
        "celery>=5.2.0",
        "pydantic>=1.8.0",
        "click>=8.0.0",
        "rich>=12.0.0",
        "typer>=0.4.0",
        "httpx>=0.23.0",
        "aiohttp>=3.8.0",
        "pytest>=7.0.0",
        "pytest-asyncio>=0.20.0",
        "black>=22.0.0",
        "flake8>=4.0.0",
        "mypy>=0.950",
        "isort>=5.10.0",
        "beautifulsoup4>=4.10.0",
        "lxml>=4.6.0",
        "openpyxl>=3.0.0",
        "pillow>=8.3.0",
        "boto3>=1.18.0",
        "google-cloud-storage>=2.0.0",
        "azure-storage-blob>=12.8.0",
        "paramiko>=2.7.0",
        "cryptography>=3.4.0",
        "jwt>=1.3.0",
        "passlib>=1.7.0",
        "bcrypt>=3.2.0",
    ],
    extras_require={
        "dev": [
            "pre-commit>=2.17.0",
            "sphinx>=4.4.0",
            "coverage>=6.3.0",
            "tox>=3.24.0",
        ],
        "test": [
            "pytest-cov>=4.0.0",
            "pytest-mock>=3.7.0",
            "factory-boy>=3.2.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)