from setuptools import setup, find_packages

setup(
    name="mock-project",
    version="0.1.0",
    description="A mock Python project for testing dependency removal tools",
    author="Mock Author",
    author_email="mock@example.com",
    url="https://github.com/example/mock-project",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "requests>=2.25.0",
        "pandas>=1.3.0",
        "numpy>=1.21.0",
        "matplotlib>=3.4.0",
        "click>=8.0.0",
        "rich>=12.0.0",
        "typer>=0.4.0",
        "httpx>=0.23.0",
        "seaborn>=0.11.0",
        "flask>=2.0.0",
        "django>=4.0.0",
        "fastapi>=0.68.0",
        "sqlalchemy>=1.4.0",
        "pytest>=7.0.0",
        "beautifulsoup4>=4.10.0",
    ],
    extras_require={
        "dev": [
            "black>=22.0.0",
            "flake8>=4.0.0",
            "mypy>=0.950",
        ],
        "test": [
            "pytest-cov>=4.0.0",
            "pytest-mock>=3.7.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)